version: '3'
services:
  codex-mongodb:
    image: mongo:7.0.0
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: codex-admin
      MONGO_INITDB_ROOT_PASSWORD: C0d3X_admin
      MONGO_INITDB_DATABASE: codex
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro