version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=codex-user
      - MONGO_INITDB_ROOT_PASSWORD=kl^vY670ol
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db